name: Build iOS Unsigned IPA
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-iOS

      - name: Unity - Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: iOS

      - name: Build Xcode Project
        run: |
          cd build/iOS
          xcodebuild -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" PROVISIONING_PROFILE_SPECIFIER="" -archivePath $PWD/build/Unity-iPhone.xcarchive archive
          mkdir -p Payload
          cp -r $PWD/build/Unity-iPhone.xcarchive/Products/Applications/Unity-iPhone.app Payload/
          zip -r ../../VisualReality.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VisualReality-Unsigned-IPA
          path: VisualReality.ipa
